### ISSUE TITLE
Noncustodial (Thread) Payments

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#10]
User should be able to send a noncustodial P2P payment

Includes any updates relevant to:
- [ ] Client code
- [ ] Contracts
- [ ] Database schema/migrations
- [ ] Chainsaw
- [ ] Any business logic (i.e. collateralization)

**Comment by ArjunBhuptani** [comment]
We didn't get to discuss this on the call, but I'd like to move towards Epics representing the process to build pieces of functionality that may or may not be separate from our release cycle. In other words, we should be able to have one epic be an ongoing feature release that spans multiple sprints or have many epics that are built/tested within one sprint.

Each epic should contain _all_ of the changes needed to have that functionality work, including tests. This means that when the functionality described in the epic is completed and merged, it should be _ready for use in production_. I think this will be a good way to move away from a `develop` branch (as per @bohendo's suggestion) but will still allow us to keep whatever is on master ready for production at all times.

The new workflow would be:
1. Create a branch off of current master (i.e. latest prod code) to represent the epic. In this case, it would be `#10-Thread-Payments`. Note that we'll have to do this step across multiple repos.
2. Branch all issues that are a part of this epic off of the epic branch. So for instance, create a `#XX-Thread-Validators` off of the above branch.
3. When done with the issue (and unit testing), merge the code back into the epic branch.
4. When all issues are completed and code is merged, do e2e and integration testing in the epic branch. Remember to pull in latest code from master here.
5. Merge into master for release.

This workflow will allow us to work on multiple pieces of functionality at the same time or one piece across multiple releases while maintaining a stable release on master at all times.

Thoughts? @LayneHaber @rhlsthrm @hthillman @bohendo @shivgupt

**Comment by ArjunBhuptani** [comment]
The main part of this that we need for Card launch is sync from latest state. Looks like right now this isn't happening properly?

**Comment by rhlsthrm** [comment]
Sync from latest state should be enabled in master and prod.
