### ISSUE TITLE
Docker versioning

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#102]
Ensures docker images have new tags

**Comment by bohendo** [comment]
One way to do this would be to give CircleCI the responsibility of incrementing the version in package.json. This means our CI would need push-to-master permissions on the relevant github repos which might be risky & we'd have to make sure it doesn't end up in an infinite loop. Not 100% sure this is even possible but if it is, it'd make things a lot simpler & safer for us devs.

**Comment by bohendo** [comment]
Ok, let's stick w a simple solution for now. I added a pre-commit hook in commit f523162 so that any commits to master will run a sanity check & confirm potential image overwrites w the user.

See `ops/pre-commit.sh` for details.
