### ISSUE TITLE
Card Documentation

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#104]
Should be finalized.

Should we also push to get the hub documentation updated as well? Do additional client docs need to be made?

**Comment by hthillman** [comment]
Yes on hub docs, maybe on client docs. When I'm done with this you should definitely review the card docs to see if any essential client stuff is missing.

**Comment by hthillman** [comment]
Card docs done (with exception of blurb on linked payments - need a hand there), need review. Have also asked a few friends from the community for feedback

**Comment by hthillman** [comment]
can i get a review from @LayneHaber @ArjunBhuptani
