### ISSUE TITLE
Dashboard: Several queries returning null

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/indra#112]
every db query that joins to _cm_channel_updates on id is returning null; assuming that it's either merging on the wrong field or there's a type issue. need to sort out for trailing 24hr data for payments, deposits, withdrawals, as well as graphs!

tagging @LayneHaber for advice on correctly IDing fields

**Comment by rhlsthrm** [comment]
Just pinged @hthillman to use the views which have many of the data he needs. We have views for `payments`, `cm_channels`, and `cm_channel_updates` which do much of the joining.

Any other joining past that should be done using the foreign key ids, which are usually `channel_id` for channels and `channel_update_id` for updates.

Very much encourage you to hook up Postico to your local db, it makes inspecting tables and generating queries much easier.
