### ISSUE TITLE
Release Cleanup

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#129]
We released dai card to mainnet!

Now we have to clean up some things. In addition to supporting dai card users + integrators, the next ten days our priorities should be:

1. Turn down knobs for collateral (1/2 day max)
2. Put threads live (2 days max)
3. Autodispute cron job (1 day max)
4. E2E Card and thread tests (2-3 days max)
5. Rewrite onchain tx service (2 days max)
6. Client dispute resolution (2 days max)
7. Documentation review and audit (2 days max)
8. IPFS saving state (3 days max)
9. Gas optimization spec for contract (3 days max)
10. Token withdrawals (1 day max)
11. Minor UI tweaks (max 2 hours per day)

**Comment by rhlsthrm** [comment]
We should split these up into issues, some of them are already done/duplicates.
