### ISSUE TITLE
Verify Validator Test Cases

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#13]
Test case for requires in contract verified. [Here](https://github.com/ConnextProject/contracts/blob/master/test/TESTSPEC.md) is full test spec to verify. Include:
- [ ] final balance always increases recipient balance on `closeThread`
- [ ] cannot open channel with contract

**Comment by hthillman** [comment]
moved: https://github.com/ConnextProject/connext-client/issues/155
