### ISSUE TITLE
Autodispute Cron Job

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#132]
Hub should autodispute channels that have been inactive for configurable amount of time, and this should run on a cron job.

This is a nice to have, mostly because the automation of this process is unnecessary. If it takes more than a day to complete, bail.

**Comment by kthomas** [comment]
@LayneHaber can we get a `provide` label to flag some of the nice-to-have functionality that seems like low hanging fruit we can provide?

**Comment by rhlsthrm** [comment]
Added `provide` label @kthomas.
