### ISSUE TITLE
Ask for the https://github.com/connext/indra/issues

### ISSUE THREAD

**Issue by lucky418** [ConnextProject/indra#1431]
Hi. one question about ContractAddress on https://github.com/connext/chaindata/blob/main/deploy.md
I'm gonna integrate the pre-deployed ERC20 token to the cross-chain bridge.
So I'm gonna build a wrapper contract for the ERC20 token.

 I checked the Anyswap frontend. In most cases, the deposit address is the same as MPC address. When we use a wrapper, which one of Wrapper and ERC20 token should be set as a contract address?

**Comment by lucky83149028** [comment]
let me move it
