### ISSUE TITLE
Hub should use NPM client

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#186]
hub should be configured to work with any npm version of the client

Can use .yalc or npm link for local development (may need to check with @bohendo about local client changes in dockerized hub)

**Comment by bohendo** [comment]
The hub is already setup to use `modules/client` for local development. After running `make` there should be a link to `modules/client` at: `modules/hub/node_modules/connext`.

All we really have to do now is change the hub's imports to point to `connext/blah` instead of `./vendor/connext/blah`
