### ISSUE TITLE
Handle payments to unopened channels more gracefully

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#194]
## Expected Behavior

Paying to a new channel is a common user flow, it should be handled gracefully w/out any errors.

## Current Behavior

Uncaught errors are thrown

## Possible Solution

Don't throw an error, log a warning maybe then return early.

## Steps to Reproduce (for bugs)

1. Send payment to fresh dai card
2. Notice `500 (Internal Server Error)` in browser console logs
3. Notice thrown error & stack trace in hub logs

## Context

It's just ugly, not a high priority issue

## Your Environment

* Version used: 0.1.13
* Browser Name and version: Brave
* Link to your project: this one 🙃

**Comment by LayneHaber** [comment]
This is handled well from the sender side with the `PT_OPTIMISTIC` payment type, which holds the payment until the receiver comes online and the payment is collateralized.

Closing this issue for now.
