### ISSUE TITLE
Block pushing versioned images if those images already exist

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#199]
## Current Behavior

If we forget to increment the version in package.json & deploy, we clobber our old images and make it harder to roll-back if something goes wrong.

## Possible Solution

Before pushing versioned images, check whether this version already exists on docker hub. If so, abort.

Something similar is already done in `indra/ops/pre-push.sh`, just gotta repackage that & activate it pre-image-push too.

**Comment by LayneHaber** [comment]
closing, should be handled by existing deploy scripts 🎉
