### ISSUE TITLE
development network is using a different port from the example

### ISSUE THREAD

**Issue by pyskell** [ConnextProject/indra#2]
The Readme example has `ganache` using port 8545, but the `development` network in `truffle.js` uses port 9545.

Need to update either the Readme example (`ganache ... -p 9545`) or `truffle.js` to use the same port.

**Comment by hthillman** [comment]
Updated! I had just been using --network ganache so this slipped by with no errors thrown.

https://github.com/ConnextProject/indra/commit/9bf1f7c80ca7416f78458a003815a4f61942e535
