### ISSUE TITLE
Accept header should be honored when errors are emitted

### ISSUE THREAD

**Issue by kthomas** [ConnextProject/indra#220]
The `accept` HTTP header is not honored if the backend throws an exception, causing JSON parsing to fail. An HTML error is being rendered instead of valid JSON as of today IIRC.

Propose following response JSON for rendering errors:

```
{
  "errors": [
    {
      "message": "something bad happened",
      "status": 422
    }
  ]
}
```

**Comment by LayneHaber** [comment]
closing, were using nats
