### ISSUE TITLE
DB migrations, no synchronize

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#235]
Right now the `synchronize` flag is set to true, this will cause problems on prod when we make changes to the DB schema that will have to be resolved manually.

Turn off this flag (or only use in dev-mode, but preferably turn off), and make sure that CI will pass.

In the future, we should use the [typeorm migrations](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md) for any schema changes.

**Comment by bohendo** [comment]
Resolved
