### ISSUE TITLE
Payment History

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#236]
Need an endpoint in the node to retrieve payment history. Should contain:
- [ ] amount of payment
- [ ] date of payment
- [ ] type of payment (link, transfer, etc)

Additionally, some non-node items:
- [ ] client should have function to hit this endpoint
- [ ] card should have the [transaction history](https://github.com/ConnextProject/card/blob/master/src/components/transactionsTable.js)

**Comment by rhlsthrm** [comment]
Metamask needs this so will up priority.

**Comment by LayneHaber** [comment]
closed by #432
