### ISSUE TITLE
State syncing

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#238]
Need to be able to sync states from clients across new devices for account recovery, and just plain usability.

Can use the hub as the source of truth here, but this is not long-term desirable.

**Comment by bohendo** [comment]
Stumbled upon a project called Fluence this weekend, might be a good place to store data where a new client device could retrieve channel state w/out placing so much trust on the hub.
It's really easy to deploy a decentralised db cluster, try it out at fluence.one/deploy
idk if you can view mine but it's at: http://dash.fluence.network/account/app/436

**Comment by ArjunBhuptani** [comment]
Closing because this will be covered by state backups + queuing issues
