### ISSUE TITLE
Pay users who don't have channels 

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/indra#24]
## Expected Behavior

Should be able to pay users who don't have channels open

## Current Behavior

Collateralization for tipping breaks

## Steps to Reproduce (for bugs)

1. Start Indra hub.
2. Load up wallet UI (http://localhost).
3. Get 1 token from MetaMask (make sure MetaMask is set to the Ganache [0] address, since that's the only one that has the tokens).
4. Deposit some amount of tokens.
5. Attempt to pay user who hasn't opened a channel and deposited

**Comment by rhlsthrm** [comment]
This works. The channel gets collateralized by the hub and then is able to be paid.
