### ISSUE TITLE
Stateless app refactors

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#240]
Our apps are installing, then immediately updating and finalizing the state.

The apps should be refactored to be stateless, where the only required action is to install and uninstall the apps, a la [swap app](https://github.com/ConnextProject/indra/blob/master/modules/contracts/contracts/SimpleTwoPartySwapApp.sol).

Deliverables:
- [ ] updated unidirectional transfer app + tests
- [ ] updated linked transfer app + tests
- [ ] update transfer service fns on the node (resolve link, install link, etc.)
- [ ] update the `ConditionalTransfer`, `ResolveCondition`, and `Transfer` controllers on the client

**Comment by rhlsthrm** [comment]
Breaking this up.
