### ISSUE TITLE
Property in store undefined on create channel

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#242]
Gazecoin is having issues trying to create channels, there is an undefined property in the store. Stack trace from [original issue](https://github.com/ConnextProject/indra-v2/issues/299):

```javascript
at new StateChannel (index.js:1209)
    at Function.fromJson (index.js:1516)
    at Store.getStateChannel (index.js:5456)
    at async getOrCreateStateChannelBetweenVirtualAppParticipants (index.js:1635)
    at async createProposedVirtualAppInstance (index.js:1603)
    at async ProposeInstallVirtualController.executeMethodImplementation (index.js:6025)
StateChannel @ index.js:1209
fromJson @ index.js:1516
getStateChannel @ index.js:5456
```

And: 

```javascript
TypeError: Cannot read property 'forEach' of undefined at new StateChannel (index.js:1349) at Function.fromJson (index.js:1622) at Store.getStateChannel (index.js:5878) at async GetFreeBalanceController.executeMethodImplementation (index.js:6150) console.<computed> @ index.js:1375
```

From [DalaiLlama](https://github.com/DalaiLlaama):
> I have traced it to a call to `getCreate2MultisigAddress(...)` in `InstallVirtualController`, that returns an address I don't recognise, and which returns nothing in the later call to `store.getStateChannel`

Using client: `@connext/client 0.0.19`
Network: Rinkeby

**Comment by LayneHaber** [comment]
If theres any information you can give on how to reproduce this, that would be helpful.

We had some issues on Wednesday with channels being created properly, and had to redeploy the contracts and node. You're using the latest client version it appears, but it looks like there's some conflicting stack traces.

In the top, I see a call to `createProposedVirtualAppInstance`, which I don't believe is hit during the original `createChannel` call

**Comment by ArjunBhuptani** [comment]
Tagging in @cf19drofxots too

**Comment by bohendo** [comment]
I think this is a bug in the store. I was getting this error in the daicard before I added [special-case handling for a couple keys](https://github.com/ConnextProject/indra/blob/master/modules/daicard/src/utils/store.js#L13).

Can anyone from Gazecoin link the repo where this issue is popping up? I suspect it'll go away if the store you pass into our client implements the same logic as what we have in the daicard: https://github.com/ConnextProject/indra/blob/master/modules/daicard/src/utils/store.js

**Comment by snario** [comment]
This may have something to do with it: https://github.com/counterfactual/monorepo/pull/2316

**Comment by bohendo** [comment]
Closing due to lack of additional info. If this issue pops up again we can open a new issue w relevant info.
