### ISSUE TITLE
Handle incorrect mnemonics better

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#244]
FYI just tracked down a tricky bug, same one I think Hunter was wrestling with a while back.

I get the following error message when trying to create a channel:

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Expected String
    at BaseX.decode (/root/node_modules/ethers/utils/basex.js:86:19)
    at Object.fromExtendedKey (/root/node_modules/ethers/utils/hdnode.js:189:32)
    at xkeyKthHDNode (/root/node_modules/@counterfactual/node/dist/index.js:321:19)
    at xkeyKthAddress (/root/node_modules/@counterfactual/node/dist/index.js:318:33)
```

It's caused when the client has the same mnemonic as the server, I noticed it when calling createChannel from our client with params:
```javascript
{
  "id": 1565178685496,
  "methodName": "chan_create",
  "parameters": {
    "owners": [
      "xpub6FC22fDx9CHAvwLLSFovJv2WKjT9pLgVBFioo5ZNoLpo2jbR5uJjv3MRNZ8FK89K7hv4iVpExf2kmrMhqBUqr7iBqa6ZJUEvzigLsoMua4g",
      "xpub6FC22fDx9CHAvwLLSFovJv2WKjT9pLgVBFioo5ZNoLpo2jbR5uJjv3MRNZ8FK89K7hv4iVpExf2kmrMhqBUqr7iBqa6ZJUEvzigLsoMua4g"
    ]
  }
}
```

Before the above, the node logged:
```
[Nest] 1   - 08/07/2019, 11:49 AM   [NodeProvider] Balance of signer address 0xB36Ce76CeAad12206828B2A97964633ABF7C2184 on rinkeby (chainId 4): 993537292000000000
```

And the twitter bot logged:
```
2019-08-07T11:51:25.155492309Z cf module signer address:  0xB36Ce76CeAad12206828B2A97964633ABF7C2184
```

We should update our client to notice this edge case & reject it w a sensible error message before passing it on to CF.

**Comment by hthillman** [comment]
@LayneHaber can this be closed? Haven't seen this pop up in awhile

**Comment by LayneHaber** [comment]
It's still an issue, haven't seen it pop up in a while because we fixed how we handle mnemonics at the app layer most likely
