### ISSUE TITLE
Stop logging the appIds array

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/indra#252]
**Expected Behavior**
appIds are not logged

**Current Behavior**
appIds are logged - 428 open apps on node 

**Possible Solution**
stop logging apps

**Steps to Reproduce (for bugs)**
view node logs

**Context**
Not a bug per se - just makes debugging more annoying

The node has 428 open apps, all of which are getting logged

Can someone point to the exact line @LayneHaber @rhlsthrm?

**Comment by rhlsthrm** [comment]
Closed by #285
