### ISSUE TITLE
In-flight deposit errors when a payment triggers another deposit

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/indra#256]
## Current Behavior

Error is triggered on transfer, after propose install

```
backend.js:6 Error: {}
    at index.js:10931
    at f (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.e.<computed> [as throw] (runtime.js:98)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:29)
```

## Steps to Reproduce (for bugs)

@LayneHaber @rhlsthrm can you describe the collateralization scenario that would cause this?

**Comment by ArjunBhuptani** [comment]
Queues up deposit -> deposits more than it should and runs through collateral

**Comment by ArjunBhuptani** [comment]
Duplicate, closing
