### ISSUE TITLE
Counterfactual app compatibilities

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#262]
**Describe the bug**
The solidity compiler version and the app imports for [our apps](https://github.com/ConnextProject/indra/blob/b83434074fff023a134fdaa26cdf7e5410c2c34d/modules/contracts/contracts/UnidirectionalTransferApp.sol#L1) and the [counterfactual apps](https://github.com/counterfactual/monorepo/blob/7165008eb9f5e11bcca9ed13b018711dc168f793/packages/apps/contracts/UnidirectionalTransferApp.sol#L1) seem to have fallen out of sync. This definitely effects the Unidirectional Transfer App and the Unidirectional Linked Transfer App, but we should probably update + redeploy all for consistency.

**Expected behavior**
These should definitely be in sync to avoid any unanticipated and hard to debug weirdness.

**Additional context**
We will have to redeploy our apps to rinkeby and mainnet. Ideally there would be some type of automated check here before deployments, but that's just an extra gold star. Would be nice to remove the legacy dependency on `@counterfactual/contracts` if possible as well

**Comment by rhlsthrm** [comment]
This should be done now, right @bohendo ?
