### ISSUE TITLE
Where did action encoding go?

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#263]
**Describe the bug**
The app registry constant seems to be missing the action encoding for the unidirectional transfer app [here](https://github.com/ConnextProject/indra/blob/b83434074fff023a134fdaa26cdf7e5410c2c34d/modules/node/src/config/config.service.ts#L110).

**Expected behavior**
All supported apps should return app encoding as well as state encoding. We may want to add a deprecated flag to apps that we formerly supported.

Probably on startup the client should finalize + uninstall any deprecated apps. (Client should generally uninstall any hanging apps IMO, but that's a UX question, most relevant if clients sign off while call is made w/in a controller).

We may want to move the uninstalling/handling of deprecated apps to a new issue that is not explicitly marked as critical though.

**Additional context**
We will eventually need to come up with some way to communicate that apps are deprecated to users, and we may not want to force uninstall. But for now I think it's okay.

**Comment by rhlsthrm** [comment]
Will separate into two issues. The deprecation issue is the non-critical portion IMO for mainnet blocker.
