### ISSUE TITLE
Plan out deprecation of apps

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#267]
**Is your feature request related to a problem? Please describe.**
We are keeping an app registry with apps that have been deprecated. We should figure out how to handle this properly with clients.

**Describe the solution you'd like**
Suggestion: Flag as deprecated, and force clients to auto-uninstall any detected deprecated apps.

**Comment by ArjunBhuptani** [comment]
Just put it in an onchain registry under a canonical label. Then we can update apps without forcing users to update client versions.

**Comment by rhlsthrm** [comment]
Well even if we pull the registry from the node (trusted) after mainnet we can update apps without updating clients.

**Comment by ArjunBhuptani** [comment]
Fixed
