### ISSUE TITLE
Allow users to pay gas costs rather than hub

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/indra#27]
## Expected Behavior

Hub operator should have option to let users pay gas costs

## Current Behavior

Hub pays all gas costs

**Comment by ArjunBhuptani** [comment]
Actually, the really easy way to do this is to just require that the user sends a tx = gas estimate in channel before the hubAuthUpdate. We'll probably need this for the Card soon so leaving this issue open.

**Comment by LayneHaber** [comment]
deprecated in favor of [#90](https://app.zenhub.com/workspaces/connext-pipeline-2019-5bf3467f4b5806bc2bf62340/issues/connextproject/indra/90)

hub operators will have configurable refund parameters on deposit, and configurable fees on withdrawals
