### ISSUE TITLE
Default to CFs Addresses

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#290]
## Expected Behavior
As we deal with the `ProxyFactory` deployment issues, it may be best to default to the address that counterfactual uses for the deployed contracts in the `migrate-contracts.js` otherwise, we may have to remember to hardcode the updates into our address book whenever there are changes there (which is not that fun).

## Current Behavior
All contracts are pulled from the relevant cf dependency, which seems to work fine for everything except the `ProxyFactory` contract. We end up having to hardcode the address into the address book, and we often forget to make sure these are in sync.

Instead, we should make sure that we default to using the cf-deployed contracts on networks where possible.

Also open to figuring out how we can replicate their deployment in our system so we can keep the current setup.

**Comment by ArjunBhuptani** [comment]
Fixed as part of mainnet contract deployment
