### ISSUE TITLE
[counterfactual] Concurrency test cases

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#297]
https://paper.dropbox.com/doc/CF-Concurrency-Test-Matrix--AkQBv0EAVqBf85sMPCwjv11VAg-iEKxNHESDBety0RnnJzIY

Need all of the scenarios outlined in the doc to work.

**Comment by hthillman** [comment]
@rhlsthrm is this blocked by ongoing CF bug? Are tests written and just trying to get them to pass?

**Comment by rhlsthrm** [comment]
Not all tests are written. The ones blank in the doc are still tbd.

**Comment by LayneHaber** [comment]
Tests are written (skipping shaded boxes, all for `takeAction`.

Likely that the results will change once the concurrency PRs are published on the CF side, but they are noted in the test

**Comment by hthillman** [comment]
I believe some progress has been made on these -- can we update the matrix?

**Comment by LayneHaber** [comment]
These are all passing in CF now
