### ISSUE TITLE
ETH deposit doesn't get confirmed

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/indra#31]
## Expected Behavior

After deposit, I should receive confirmPending status and then the transaction should get confirmed, and funds should show up in the channel.

## Current Behavior

When I deposit, i get a proposependingdeposit back, everything gets signed correctly, the console tells me the update was sent to chain. But nothing shows up in chainsaw, I don't get confirmPending, then eventually it times out and nothing ever gets deposited to channel.

`Sending userAuthorizedUpdate to 0x9fbda871d559710256a2502a2517b794b482db40: in mempool: 0x1001f5856382df053221a5b8ae06511135d315113b012dfdf68438e094143038`

## Steps to Reproduce (for bugs)

1. Launch indra from branch UI-flow
2. Deposit ETH

## Context

Trying to bundle some actions together to improve UX.

**Comment by rhlsthrm** [comment]
I tried this and it worked for me. It could be a setup issue.
