### ISSUE TITLE
[Client] Add support for STREAMING_TRANSFER payment type under `conditionalTransfer` client endpoint

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#313]
**Is your feature request related to a problem? Please describe.**
Allow for "set it and forget it" streaming payments - this is much better UX for platforms like dTok/Pitch Investors Live and is an important payment primitive.

**Describe the solution you'd like**
A quick guide on how to do this:

**Step 1:** Add relevant types here: https://github.com/ConnextProject/indra/blob/master/modules/types/src/index.ts
- [ ] Add `STREAMING_TRANSFER` type to `TransferConditions` ENUM
- [ ] Add `StreamingTransferParameters` and `StreamingTransferResponse` types (params should be something like: `amount`, `assetId`, `recipient`, `rate`, `startBlock`)
- [ ] Add `ResolveStreamingTransferParameters` and `ResolveStreamingTransferResponse` types (param should probably just be `sender` unless you want to allow multiple payment streams per sender/receiver combo)
- [ ] Add above to `ConditionalTransfer` union types

**Step 2:** Write StreamingTransfer app
- Standardized app interface/guide: https://specs.counterfactual.com/en/latest/app-definition.html
- Example app (above linked transfer app): https://github.com/ConnextProject/indra/blob/master/modules/contracts/contracts/UnidirectionalLinkedTransferApp.sol

General strategy here: you probably don't need to write an `applyAction` or `getTurnTaker` fn. Just have the app state include startingBlock and balance, which get set on install. For `computeOutcome`, compute the ending balance as current block number minus `startingBlock` times the rate. This would let either party call `resolveCondition` in the client which would `computeOutcome` and uninstall the app.

**Step 3:** Add the new app to the `conditionalTransfer` controller in client: https://github.com/ConnextProject/indra/blob/master/modules/client/src/controllers/ConditionalTransferController.ts

You should be able to generally copy the existing implementation for linked transfers. Some gotchas:
1. **Use installVirtual not install** - see the `transfer` controller for how to call this
2. `resolveCondition` should just call `uninstallVirtual` instead of `takeAction` since the app doesn't use an `applyAction` fn.

I believe that should be it. @LayneHaber anything I'm missing here? What's the best way to test this?

**Comment by rhlsthrm** [comment]
@ArjunBhuptani we should point at this as the example, since it already follows the "general strategy" you outlined: https://github.com/ConnextProject/indra/blob/master/modules/contracts/contracts/SimpleLinkedTransferApp.sol

**Comment by ArjunBhuptani** [comment]
Right, the only issue with the above is that it's using two (ledger) app (i.e. one between the sender and hub and one between hub and receiver), which is different from using a virtual app (between sender and receiver OVER hub)

**Comment by ArjunBhuptani** [comment]
Closing this because it's stale and we're moving away from virtual apps for now.
