### ISSUE TITLE
Withdraw tokens

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#32]
## Expected Behavior
Right now we only withdraw ETH, with an exchange. We need to be able to withdraw tokens as well.

## Current Behavior
Withdraw exchanges tokens into ETH based on the exchange rate.

## Possible Solution
I think everything exists to make this happen, we just need to pass in the correct parameters.

**Comment by ArjunBhuptani** [comment]
Have an open question on this in #41

**Comment by ArjunBhuptani** [comment]
Will happen on future release (deeper generalized user/hubAuthUpdate refactor)
