### ISSUE TITLE
Client going offline prematurely

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#322]
**Describe the bug**
Get rid of polling, listen for method name instead of event name.

**Comment by hthillman** [comment]
@LayneHaber @bohendo can you provide more context / a path forward here? is this a blocker?

**Comment by ArjunBhuptani** [comment]
Was this fixed by https://github.com/ConnextProject/indra/pull/312?

**Comment by rhlsthrm** [comment]
Fixed by #312

**Comment by ArjunBhuptani** [comment]
Looks like it was indeed fixed by #312
