### ISSUE TITLE
[node] Add NATS auth

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#325]
We need to auth the NATS endpoints especially the lock service calls.

**Comment by kthomas** [comment]
Something along the lines of this to generate a certificate authority and begin issuing client certs:

```
# create certificate authority
openssl genrsa -des3 -out ca.key 4096
openssl req -x509 -new -nodes -key ca.key -sha256 -days 365 -out ca.pem

# create ca-signed client cert
openssl genrsa -out peer.key 4096
openssl req -new -key peer.key -out peer.csr
openssl x509 -req -in peer.csr -CA ca.pem -CAkey ca.key -CAcreateserial -out peer.crt -days 365 -sha256 -extfile peer.ext
```

**Comment by kthomas** [comment]
Need to look into how we support client auth for a plurality of certificates.

**Comment by bohendo** [comment]
Any random client should be allowed to send messages & interact w their own stuff by default where "their own stuff" is defined by the key pair they control (verified w a sig) compared to some multisig's owners or some app instances participants. Some of the subjects eg `config.get` should be publicly available for anyone to query too. I don't understand what problem a cert authority would be solving here though @kthomas

**Comment by hthillman** [comment]
Any update here @bohendo?

**Comment by rhlsthrm** [comment]
I think we need to chat with @kthomas and scope this out.

**Comment by kthomas** [comment]
Let's schedule some time to discuss 👍

**Comment by ArjunBhuptani** [comment]
Part of #334 meta-issue

**Comment by kthomas** [comment]
> Tentative auth flow:
> 
> 1. New client wakes up
> 2. Client sends nats message w subject `config`
> 3. `config` subject is open to the public so the node responds w config info
> 4. Client sends nats message w subject `channel.create.*`
> 5. `channel.*` messages are protected so this message is either not propagated or ignored by hub
> 6. Client asks node to authenticate
> 7. Node gives client a nonce to sign
> 8. Client signs & gives sig to node
> 9. Node checks sig, if it's good it issues a cert to the client
> 10. Client tries to send message w `channel.create.*` subject again
> 11. Hub checks cert & verifies this client is allowed to access this subject so it responds
> 
> This sounds like what you're thinking @kthomas?

@bohendo thanks for sharing this, insightful and good context for me as I am beginning to research NATS options re: client auth vs. vending signed JWT.

I am particularly curious as to how to protect NATS directly vs. depending on the hub as an authorization proxy, as that implies our solution would not scale to support a future iteration when NATS looks more like a mesh network. I am hoping we can architect this such that the hub will be indeed be responsible for signing credentials, but the NATS instance will be able to dynamically use those credentials. So, that is to say, item #11 in your list above breaks down as we actually need NATS to be aware of our authentication and authorization strategy (authentication meaning yes, that user is valid and authorization meaning the authenticated user has sufficient permission to interact with a whitelist of subjects). Bonus points here if we can authorize publish and subscribe independently on NATS subjects. I have doubts that the authentication facilities are that robust just yet... hoping to find that out shortly.

Updates forthcoming.

**Comment by kthomas** [comment]
Update:

NATS actually has support for subject-level authorization and it is implemented with the granularity we need... and nearly exactly as we discussed (see https://nats-io.github.io/docs/nats_server/authorization.html). Awesome...

The approach is to allow the hub to vend JWT tokens for users upon request, signing the JWT using the `RS256` algorithm. NATS will be aware of the public key used to sign the JWT so it can verify the signature and trust the authorized scope (i.e. publish/subscribe privileges, per subject id) presented in the payload of the JWT. **This is not yet a supported authentication strategy supported by NATS.**

I am going to make a NATS PR that adds support for an arbitrary JWT to be presented by clients for authentication and authorization. NATS server will use the hub's public key to authenticate the user and verify that it can trust the embedded authorization.

Next update should include a link to that PR.

**Comment by kthomas** [comment]
For posterity as a lot of discussion happened earlier... current status of this:

As per our discussion this morning, the PR for adding support for bearer JWT authorization to NATS server is going to require proper due diligence to get it ready for review. There is an appetite for this authorization strategy among the creators/core maintainers of NATS so getting a proper PR ready for review and probable inclusion in the next release of NATS will take another week or two but it is well worth it. While that PR is pending and possibly even prior to the first release of NATS which includes our prospective functionality, we will maintain a fork.

When running the NATS server fork, enabling JWT bearer authorization will simply require the presence of a `JWT_SIGNER_PUBLIC_KEY` in the environment. Bearer tokens signed with the private key (i.e., by the hub) will present the following in the JWT payload: `{"data": {"permissions": "publish": [], "subscribe": [] }}`. See [NATS Authorization](https://nats-io.github.io/docs/nats_server/authorization.html) docs for valid `permissions` options. In other words: in this model the hub is delegating authorization to NATS server when it vends a JWT signed by its private key.

Our bearer tokens will have a short ttl (i.e., `exp` default to something like +1 hour from the `iat` issued at timestamp; i.e., `exp := Date.now() + 3600000`). NATS clients will be responsible for gracefully "refreshing" tokens prior to expiration of the previously signed bearer token and using the latest valid credentials upon reconnect.

After the above strategy works, we need to circle back and support (i) [TLS](https://nats-io.github.io/docs/developer/security/tls.html) and (ii) the use of our NATS connections with NATS streaming server to enable message durability and [encryption at rest](https://nats-io.github.io/docs/nats_streaming/store-encryption.html).

I will add a link to the testing branch I have been spiking as soon as it's ready-ish.

@bohendo

**Comment by kthomas** [comment]
Here is a nats-server branch that we can use for testing: https://github.com/kthomas/nats-server/tree/jwt-bearer-auth

@bohendo reach out to me before you get started to confirm which sha to use.

**Comment by kthomas** [comment]
Preliminary NATS server PR has been opened: https://github.com/nats-io/nats-server/pull/1149

**Comment by rhlsthrm** [comment]
What more needs to be done with this @bohendo @kthomas?

**Comment by ArjunBhuptani** [comment]
Added to our sprint taskboard. @kthomas let's chat asap?

**Comment by kthomas** [comment]
🙌
