### ISSUE TITLE
"Caught error unlocking resource" during deposit to card UI

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#329]
**Describe the bug**
Hub logs the following during deposit on the card UI.

```
[Nest] 1   - 09/19/2019, 2:12 PM   [LockService] Caught error unlocking resource 0xBD0F0408F2Bb231182dAB1cB1F0dd0b9254E179d +3ms
{ LockError: Unable to fully release the lock on resource "0xBD0F0408F2Bb231182dAB1cB1F0dd0b9254E179d".
    at loop (/root/node_modules/redlock/redlock.js:265:18)
    at tryCatcher (/root/node_modules/standard-as-callback/built/utils.js:11:23)
    at promise.then (/root/node_modules/standard-as-callback/built/index.js:19:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'LockError',
  message:
   'Unable to fully release the lock on resource "0xBD0F0408F2Bb231182dAB1cB1F0dd0b9254E179d".',
  attempts: undefined }
```

Deposits get stuck after this error is throw but refreshing the page unsticks it and the deposit appears to be complete after the page reloads w a properly-increased in-channel balance.

**To Reproduce**
1. Go to staging.indra.connext.network
2. Send some eth to the card's address & wait
3. View hub logs to see the above error

TODO: test locally

**Expected behavior**
Deposit should work w/out an errors on the hub & w/out needing to refresh the page

**Comment by bohendo** [comment]
Same error occurs whether depositing to a fresh account or one that's already redeemed a link aka already has collateral.

**Comment by LayneHaber** [comment]
Tried locally with a 15s blocktime (same as rinkeby) and was able to reproduce. feel free to check out [this](https://github.com/ConnextProject/indra/tree/329-lock-error) branch with that change temporarily added.

Couldn't locally repro with automining, but the ttl of the lock is 30s so a 15s blocktime shouldn't cause these weird issues and yet...

**Comment by rhlsthrm** [comment]
Actually TTL was not getting passed through and set to 30s on our side.

**Comment by rhlsthrm** [comment]
Fixed.
