### ISSUE TITLE
[protocol] Move contract deployment to withdraw

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#331]
**Is your feature request related to a problem? Please describe.**
We're gonna be bleeding gas money as long as we're opening new channels for everyone who visits the daicard ui.

**Describe the solution you'd like**
Don't create the user's channel until they've committed to depositing. Channel creation really shouldn't happen on `connect`, that should be a separate function.

**Comment by ArjunBhuptani** [comment]
Being worked on here: https://github.com/counterfactual/monorepo/pull/2467
