### ISSUE TITLE
Deploy mainnet contracts

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#335]
Blocked by changes requested by audit related to `isFinal` call. I believe @snario is currently working on this.

Once last change is submitted & all audit feedback is accounted for, we'll be ready to deploy to mainnet.

Prerequisite: investigate & solve #290

**Comment by ArjunBhuptani** [comment]
Currently blocked by merging this PR: https://github.com/counterfactual/monorepo/pull/2443

**Comment by ArjunBhuptani** [comment]
Done
