### ISSUE TITLE
Cannot transfer to uncollateralized (online) xpub

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#348]
**Describe the bug**
Transfers to uncollateralized recipient fails and loop continuously without recollateralizing.

**To Reproduce**
1. Transfer to an uncollateralized but online address.

**Expected behavior**
Receiver collateralizes.

**Comment by ArjunBhuptani** [comment]
Fixed: https://github.com/ConnextProject/indra/pull/351
