### ISSUE TITLE
[dashboard] Create dashboard for v2

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#354]
## Context

* Client version used:
* Node version used:
* Chain used: 
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by hthillman** [comment]
Today: Learned about proxies, got Hasura dashboard running locally.

Next steps: hopefully get deployed. And then see what tooling/notifications I can easily build on top of Hasura

**Comment by hthillman** [comment]
Need to add Hasura user to db entry script.. @bohendo can you advise here? I see where the postgres user is assigned, but I don't see where permissions are granted

https://docs.hasura.io/1.0/graphql/manual/deployment/postgres-permissions.html#postgres-permissions

**Comment by hthillman** [comment]
Hasura working, proxy WIP

https://github.com/ConnextProject/indra/pull/374

**Comment by hthillman** [comment]
Wrestled with proxy for awhile today. Didn't go well. Keeps resolving to Dai Card instead of `/hasura/`. All changes are pushed

cc @bohendo when you're back and rested up.

**Comment by hthillman** [comment]
currently failing CI. appears to be trying to reference a network that doesn't exist. still digging here.

https://circleci.com/gh/ConnextProject/indra/7272?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ArjunBhuptani** [comment]
Merged, closing
