### ISSUE TITLE
[card] Swap/withdrawal weirdness

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#357]
**Describe the bug**

This error appears when withdrawing, then the card freezes:
```
SwapController.js:239 Uncaught (in promise) Error: Value (56232526450797099) is not less than or equal to 0
    at n.<anonymous> (SwapController.js:239)
    at f (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.S.forEach.t.<computed> [as next] (runtime.js:98)
    at o (SwapController.js:21)
```

**To Reproduce**
Deposit into daicard, and withdraw to an outside address. This error should pop up in the console. When you try to deposit again, the autodeposit will not kick in.

Fixed by a refresh though.

**Comment by ArjunBhuptani** [comment]
Is this still reproducible?

**Comment by LayneHaber** [comment]
Closing, could not repro
