### ISSUE TITLE
Setup better e2e tests

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#36]
## Expected Behavior

Manually clicking through channel operations after every code change is tedious and lazy people like me tend to just not do it.

We need an automated way to test the wallet's logic and it's interactions with the hub code.

Given my painful experiences writing selenium-based e2e tests, I'm going to suggest we explore [Cypress](https://www.cypress.io/) as an alternative first before trying to incorporate the traditional e2e test stack.

Run `npm install cypress` and then figure it out from there

**Comment by LayneHaber** [comment]
Ideally would like to get this test framework in place before we launch, thoughts on timing @ArjunBhuptani @rhlsthrm @bohendo ? 

Had these in place with the previous client/hub/wallet architecture

**Comment by bohendo** [comment]
Closing this issue since e2e tests would be more relevant in the card repo. e2e tests in the hub hardly make sense anymore since we've stopped using the wallet. Buuut they might make sense in the future as we continue to build out the dashboard. Once that future comes, we can reopen a similar issue.

**Comment by bohendo** [comment]
Closed in favor of https://github.com/ConnextProject/card/issues/21
