### ISSUE TITLE
Demo Wallet UI Updates

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#42]
We should make the UI for the wallet a little cleaner prior to demoing it further. UI mockups coming here soon.

This one's high priority so that we can get it out asap.

**Comment by ArjunBhuptani** [comment]
![screenshot from 2019-01-15 07-30-58](https://user-images.githubusercontent.com/22877754/51205961-e6b3ba00-18bb-11e9-8936-fd646e6b1eb3.png)

**Comment by hthillman** [comment]
@ArjunBhuptani in the above diagram:
1) What's the function of the `reselect signer` button?
2) Do you think we need to have something for the user to see browser wallet mnemonic? Or if everything sent to the wallet just gets automatically deposited, it's probably a moot point..

**Comment by rhlsthrm** [comment]
@hthillman I think we need the browser wallet mnemonic. We will eventually need a "recover from mnemonic" function as well.

**Comment by ArjunBhuptani** [comment]
Oh sorry. There should be multiple screens here. Onload, it should popup with a modal that has you choose your signer. Either you choose metamask or the browser. If the latter, it creates a browser wallet, shows you the mnemonic and then you hit accept and it takes you to the normal page.

`reselect signer` is effectively the same as "create a new browser wallet" except it gives you the option of having metamask be your signer instead (obviously this would now be a new channel so maybe that's going to be an issue here?)

In general, I want to get rid of the "browser wallet" terminology and just have user choose a signer

**Comment by ArjunBhuptani** [comment]
Having the mnemonic is still necessary even if everything gets deposited immediately (which it should). You need it in order to recover funds in your channel if you lose your signer.

**Comment by ArjunBhuptani** [comment]
Gonna thing through colors some more tomorrow and get back to you on those

**Comment by hthillman** [comment]
Awesome, starting on the signer flow now. Update on where the rest of things stand (lots of fiddly css things to go, but most of the pieces are in place):

![image](https://user-images.githubusercontent.com/35902552/51332802-696a7f80-1a4a-11e9-8dfa-351dc2ee7fce.png)

**Comment by hthillman** [comment]
Yep, will do. I wrote some placeholder tooltip text but it could use some work.

**Comment by hthillman** [comment]
Remaining todos

1) merge in the most recent hub/client code (high priority)
2) make it work end to end (high priority)
3) add wallet recovery/key entry functionality (medium priority)
4) add buttons for collateralization and reselecting signer (medium priority--collateralization will be very easy, reselecting signer will probably take a lil more work)
5) mnemonic not showing up on getKey (medium priority, after adding recovery functionality)
6) fiddly css stuff, colors, spacing etc (low priority)
