### ISSUE TITLE
[card] Build "upgrade" path in v2 dai card for existing v1 users

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#435]
We chatted about this in person at Devcon - Bo's suggestion was to have an automated UI prompt for any existing Dai Card (v1) which forces the user to "upgrade".

When the user hits the upgrade button, funds are withdrawn from the v1 Dai Card and then deposited to the v2 one.

Things we'll need for this:
- Localstorage variable to keep track of whether to show the v1 upgrade prompt or not
- UI component which the user clicks to upgrade (plus text such as "withdrawing from v1", "depositing to v2" so that users know what they're waiting on)
- Integrating v1 client into the v2 Dai Card and wiring up withdrawal

**Comment by LayneHaber** [comment]
#437
