### ISSUE TITLE
[card] Recipient coming back online with pending async transfers seems to break

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#444]
**To Reproduce**
1. Receive transfer when offline
2. Come online to retrieve the transfer

**Comment by LayneHaber** [comment]
Can't reproduce, tried:
- single awaiting async payment
- multiple awaiting async payments
- large value (recipient undercollateralized) async payment

**Comment by ArjunBhuptani** [comment]
Not able to reproduce this on staging either - closing
