### ISSUE TITLE
Unilateral Disputes

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#45]
## Expected Behavior
Hub should be able to unilaterally close disputes, client should handle this appropriately and recover channel as needed.

## Context
Allows hub to reclaim collateral from offline users unilaterally.

**Comment by LayneHaber** [comment]
@ArjunBhuptani do we want to make sure the client response is included in mainnet?

There are some branches, they got blocked from the sync issue, but that should be cleared now.

AFAIK the dispute responses that exist are only for channels without threads. We should make sure the hub (at least) can initiate and respond to thread disputes properly as well.

**Comment by ArjunBhuptani** [comment]
no it's fine, we can do this later. This would be a time consuming change. I want to be done with all code changes today or tomorrow
