### ISSUE TITLE
Yarn/Node version locking downstream issues

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#461]
Caused by upstream CF packages.

See: https://github.com/counterfactual/monorepo/issues/2394

This issue is being opened largely to keep track of the problem in our own sprint workflow

**Comment by rhlsthrm** [comment]
This is only an issue because we are having trouble updating to CF version 0.2.83.

**Comment by ArjunBhuptani** [comment]
For reference: https://github.com/ConnextProject/indra/pull/466 updates CF to 0.3.0 so that should take care of this issue too

**Comment by rhlsthrm** [comment]
This should be fixed now.
