### ISSUE TITLE
[protocol, card, client] Unrolled Deposit

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#462]
Separate out the deposit commitment from the onchain deposit transaction itself.

WIP: https://github.com/counterfactual/monorepo/issues/2516

**Comment by ArjunBhuptani** [comment]
This should also include the necessary changes to client/card to support the new deposit type.

Doing so will fix a lot of the pesky bugs we're seeing with autodeposit int he card too

**Comment by rhlsthrm** [comment]
Implementation details from Liam:

- Create a new controller on cf-core that looks similar to the deposit/withdraw controllers (INSTALL_BALANCE_REFUND).
- The controller will install a balance refund app and set a flag in the channel saying that the balance refund app is installed.
- Create another controller that removes the balance refund app and sets the flag to false.
- Deposit and withdraw should throw errors if they are called when the balance refund app is installed. An alternative approach is to make those controllers smarter and automatically do the uninstall.

Indra implementation of these controllers:
- The client can always have the balance refund app installed unless the hub is depositing.

**Comment by rhlsthrm** [comment]
For the edge case where there is a small window when async deposit can be wrongly credited to the hub, use the following workaround:
- Hub checks free balance before deposit
- If free balance after - free balance before > deposit amount, credit back to client's channel

**Comment by rhlsthrm** [comment]
New updates to feature:

1. remove timeout from client API
2. remove any rescinding logic from the hub
3. add checks in the hub to refuse to deposit if the user has a coin balance refund app installed
4. on daicard make the timer a button (should display something like 
```
if (coinBalanceRefundAppInstalled with recipient == user) {
   ready to accept deposits
} else {
   deposit inactive
}
```
5. Add check on load in daicard for the multisig balance:
```
if (multisigBalance > threshold) { uninstall } else { listener for asset id }
```
6. The UI tests will need fixing

**Comment by rhlsthrm** [comment]
The primitive functions are already in the client so the use case can be supported at the app layer. Closing this issue.
