### ISSUE TITLE
[card] Deposit then immediate withdrawal bug

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#464]
Reported by Bruno from Metamask. Steps to repro:

* Deposit in card
* Immediately withdraw after deposit completes (after the number shows up)

FYI, I could not reproduce this locally when I tried.

**Comment by LayneHaber** [comment]
Going to prioritize #462 (which changes deposit fns), and come back to this afterwards to see if it is resolved or easier to repro

**Comment by ArjunBhuptani** [comment]
Instead of hunting the bug, let's add an e2e test to check if this passes.

**Comment by LayneHaber** [comment]
Fixed in #640 but still needs an e2e test
