### ISSUE TITLE
[node, client] Nameserver for pubs

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#468]
Node-hosted registry of names to xpubs. The registry can have a signature that verifies that the name matches the xpub to keep it trustless.

**Comment by ArjunBhuptani** [comment]
Gonna look into whether this can be done easily with ENS. If not, we can just hack something together here and figure it out later

**Comment by ArjunBhuptani** [comment]
Found a way to do this easily via ENS - closing
