### ISSUE TITLE
[node, client] Restore state doesnt fully ... restore state

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#472]
**Describe the bug**
Some, but not all, of the state is properly restored when importing the mnemonic

One of the things that is _not_ restored is the channel nonce, which is used to derive the app ids, so no app would be successfully installed on an imported channel.

**To Reproduce**
Make a channel, do some stuff, try to restore channel, and do stuff.

**Expected behavior**
It'll do the stuff

**Comment by LayneHaber** [comment]
Closing this as #466 will include major updates to the restore mechanism.

Can reopen the issue if it continues to appear.

**Comment by LayneHaber** [comment]
Similar behavior reported by a user, likely similar bugs will happen when we migrate channels to use the new store

**Comment by rhlsthrm** [comment]
@LayneHaber is this still an issue?

**Comment by LayneHaber** [comment]
Restore has been overhauled, don't think this is an issue anymore. Think this was likely related to the multisig things we were dealing with. Closing.
