### ISSUE TITLE
React Native error with `eccrypto`

### ISSUE THREAD

**Issue by thowar2** [ConnextProject/indra#474]
The library `eccrypto` causes errors with react native when using `conditionalTransfer`

![Screen Shot 2019-10-24 at 12 21 52 PM](https://user-images.githubusercontent.com/3210789/67584633-46f35880-f778-11e9-99d6-b25402794889.png)

This is due to dependencies used by `eccrypto`, issue logged there as well https://github.com/bitchan/eccrypto/issues/45

**Comment by ArjunBhuptani** [comment]
Looks like there's a shim to fix this already? https://github.com/vacuumlabs/rn-nodeify

**Comment by ArjunBhuptani** [comment]
Fixed - implementing a sample repo + docs here: https://github.com/ConnextProject/indra/issues/585
