### ISSUE TITLE
[card] Detect if wallet-connected signer is offline

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#477]
## Expected Behavior
Wallet connect should detect and display a warning if the connected signer is offline, and not take any further channel actions

## Current Behavior
There is no detection on the connected side, meaning the channel actions will just hang after being routed to the "smart" client

**Comment by ArjunBhuptani** [comment]
Stale, moving here until we reprioritize it: https://github.com/ConnextProject/indra/issues/620
