### ISSUE TITLE
Don't use payment bot for ui transfer tests

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#507]
We have async transfers working so we don't need to anymore. UI tests will run a lot more quickly and, at the moment, we're not even testing card-to-card transfers which is what we should really be doing.

**Comment by ArjunBhuptani** [comment]
We should still have async transfers check recipient balance right? How would we do that without a bot?

**Comment by bohendo** [comment]
Oops, this chore has already been completed.

Using the payment bot was super fragile and balance checks were actually turned off bc they were so inconsistent. With async transfers the UI testing flow is now:
 - open new daicard, get it's xpub & address & mnemonic
 - burn & create another new daicard
 - deposit into second card & send to first xpub
 - restore first mnemonic & check balance display

No more regex-parsing bot output: yay. Just gotta check the UI for balances

**Comment by rhlsthrm** [comment]
@bohendo one issue I'm still seeing is that we aren't testing the "synchronous" portion of async transfers which uses a different mechanism than the async version (i.e. using the NATS subscriptions). We should make a different issue for this, and I'm not sure if it's possible using browser clients.

**Comment by bohendo** [comment]
Well we are testing sync transfers in the bot tests. The daicard doesn't use sync transfers in any way so it doesn't really make sense for that to be tested as part of the UI tests.

**Comment by rhlsthrm** [comment]
> The daicard doesn't use sync transfers in any way so it doesn't really make sense for that to be tested as part of the UI tests.

I don't mean the sync transfer as in the p2p transfer. The async transfer itself behaves differently if the recipient is online. The recipient sets up a NATS subscription for the message and will instantly resolve the payment if it's online. This is different than async, where the client comes online and the hub pulls the transfer out of its DB.
