### ISSUE TITLE
[client, card] Swap app weirdness

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#527]
Sometimes the msg emitted from the node seems to have the wrong type. The balances are successfully updated, but it is weird.

Will likely require a special function to pull message from the data in various forms.

See attached screenshot.

![Screen Shot 2019-11-07 at 11 10 02 AM](https://user-images.githubusercontent.com/12769011/68419597-62366e80-014f-11ea-8d8a-02e8d3b3a2f7.png)

**Comment by ArjunBhuptani** [comment]
Linked to #558
