### ISSUE TITLE
[card, client] Withdraw never resolves

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#528]
Withdrawals are successful, but the function never resolves (likely cannot find matching transaction).

Only happens sometimes, refresh fixes on card. See screenshots:

![Screen Shot 2019-11-07 at 11 14 33 AM](https://user-images.githubusercontent.com/12769011/68419802-cbb67d00-014f-11ea-9e63-6ee1a1cf26cd.png)

**Comment by ArjunBhuptani** [comment]
If function doesn't resolve, then the spinner wont stop so make sure the cypress withdrawal test doesn't pass if the spinner doesn't stop.

**Comment by ArjunBhuptani** [comment]
Stale and probably not really relevant anymore after new withdraws. Closing.
