### ISSUE TITLE
Set inflightCollateralization to f if error occurs while collateralizing

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#547]
**Describe the bug**

eg if the node has balance too low and we try to collateralize it errors out while inflightCollateralization is set to true blocking any future attempts to collateralize

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**

* Client version used:
* Node version used:
* Chain used: 
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Additional context**

**Comment by rhlsthrm** [comment]
@bohendo looks like this happens here: https://github.com/ConnextProject/indra/blob/master/modules/node/src/channel/channel.service.ts#L126

Can we close this?
