### ISSUE TITLE
[node] Tracker: Simplify/standardize stores

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#549]
Now that we don't store the mnemonic/priv key, we don't need to nest values within an object that is keyed by the key. We can simplify the store slightly by doing this.

For example, now:
```
const record = {
  key: "SOME_KEY",
  value: { SOME_KEY: <actual value> }
}
```

Can instead be:
```
const record = {
  key: "SOME_KEY",
  value: <actual value>
}
```

See comments in `modules/node/src/cfCore/cfCore.repository.ts` for details.

**Comment by ArjunBhuptani** [comment]
Making this a tracker issue and upgrading priority.

We should do the above and find ways to simplify/standardize stores. This includes not only store implementations but also hardening the client to throw error on stores that are implemented incorrectly.

**Comment by LayneHaber** [comment]
Proposed changes document by @bohendo [here](https://paper.dropbox.com/doc/State-Store-API--AoDN12QK8hUHDtS1qP414m2lAQ-mq428nofu2sY4tMRaBs7q)

**Comment by ArjunBhuptani** [comment]
This work is now happening in https://github.com/ConnextProject/indra/issues/845 along with a PR that was merged https://github.com/ConnextProject/indra/pull/834

Closing

**Comment by ArjunBhuptani** [comment]
This work is now happening in https://github.com/ConnextProject/indra/issues/845 along with a PR that was merged https://github.com/ConnextProject/indra/pull/834

Closing
