### ISSUE TITLE
Need a way to see onchain channel balance

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#55]
I want to see onchain channel balance so I can see if there is any ETH in the browser wallet (i.e. for token deposits).

**Comment by hthillman** [comment]
There will never be any onchain channel balance, it's on a poller to autodeposit to the channel. If that's not the correct behavior we can change it.

**Comment by rhlsthrm** [comment]
But if there's no ETH it can't auto deposit tokens. How are we handling that?

**Comment by hthillman** [comment]
See #56, we probably need to change the behavior but we should talk about how exactly it should work

**Comment by bohendo** [comment]
The term "onchain" is ambiguous in this context.. Lots of things have balance on chain (metamask, browser wallet, hub account, contract, etc).

I assuming that what you're referring to here is the browser wallet aka the cookie mnemonic aka the autosigner?

**Comment by bohendo** [comment]
I agree though, we might not want to put the autosigner wallet front & center but it's address & balance & privkey/mnemonic should be available somehow, if nothing else so advanced users can sweep the gas money & debug more effectively.
