### ISSUE TITLE
[client, node] Virtual install is broken

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#551]
Old virtual install flow will not work anymore. The new flow needs to be:

- Client A proposes an install to Client B
- Client B checks if it has a channel with Client A
- If channel exists, install as ledger app
- Otherwise, install virtually

This is not critical for our current iteration where we do not install virtually.

**Comment by ArjunBhuptani** [comment]
Covered by: https://github.com/ConnextProject/indra/issues/600
