### ISSUE TITLE
[cf-core] Inconsistent types

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#558]
Sometimes app instances/proposed app instances in the store are stored as objects, and sometimes they are stored as arrays. 

Sometimes you get `msg.data.data` sometimes you get `msg.data`

These should all be cleaned up so they are consistent.

Footnote: also investigate where it is `[null] vs []` when getting passed to fromJson to eliminate [this](https://github.com/ConnextProject/indra/blob/0dcc302f3bc3c0a1ae42312f1be43b303b8c3d3e/modules/cf-core/src/models/state-channel.ts#L538) fix

**Comment by rhlsthrm** [comment]
Objects vs arrays should be solvable in the `fromJSON` function. Not sure if that affects the operation when its a map. Let's track down when each of these things happens.

**Comment by LayneHaber** [comment]
It doesn't affect the actual operation, but there's a few inconsistencies with the types that I'd like to clean up.

**Comment by ArjunBhuptani** [comment]
Merged - follow up work is happening in https://github.com/ConnextProject/indra/issues/574
