### ISSUE TITLE
Depositing only tokens doesn't work if there is no ETH in the channel.

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#56]
Maybe we should block token deposit if the onchain ETH balance of the signer is 0?

**Comment by hthillman** [comment]
Related to #55, right now the eth balance will always be zero because there's an autodeposit poller. This behavior follows spank's paradigm, should we reevaluate? maybe have the autodeposit poller reserve a small amount of eth in the browser wallet for token deposits?
