### ISSUE TITLE
[card] ENS support

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#562]
**Is your feature request related to a problem? Please describe.**
xpubs are soooo ugly.. and eth addresses for that matter.

**Describe the solution you'd like**

Resolve ENS names. 2 places we juggle ugly strings: sending to some xpub and cashing out to some eth address.

Cashing out to an eth address is easy bc the public ENS resolver can resolve address records pointing to an on-chain address.

Sending to an xpub derived from an ens name is a little trickier. An EIP will be submitted to either add an xpub-type record an xpub key to the text record. This will take a while, in the meantime we can hijack the description key of an ens name's text record.

When it's all done, I should be able to cashout to bohendo.eth (by pulling the address from bohendo.eth's address record) or send from another daicard to bohendo.eth (by retrieving an xpub from the description key from bohendo.eth's text-record).

Obviously, this will require a bit of internal verification (eg the data in the text-record's description key needs to be a valid xpub) and end-user verification (eg display the derived xpub/address in small-but-readable text at the bottom of the input field so tech-savy users can sanity check that their name was resolve to the correct value.

Once completed, we can point Metamask & other projects to this solution as a reference implementation for their own app's ENS support

**Comment by ArjunBhuptani** [comment]
Need to update to use the new key that Bruno suggested:

`VND.CONNEXT: ${xpub}|${chainId}`

**Comment by ArjunBhuptani** [comment]
Done, closing
