### ISSUE TITLE
Polish daicard UI

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#567]
Our styling is kinda wild & there's definitely room for improvement.

@hthillman got some much-needed cleanup started & opened up some points for discussion. A few open questions:

1. Should send functionality be on the home screen? @ArjunBhuptani isn't a fan but I really like having the card's balance in the top bar, if the balance goes there then the homescreen is left kinda bare so we should add something more interesting there.. Our friend pico on Discord pointed us towards some really nice wallet UIs that we could model and a lot of these have tx history on the home screen. This seems like a great thing to add to the homescreen to me.

2. Color theme. Currently white background w some black and orange. Making things a lot more white got some pushback and the new dark theme feels like an improvement but still doesn't seem quite right. I'd recommend we copy https://uniswap.exchange/swap and use a dark theme w a couple different shades of dark grey.

Any other points to discuss before we're ready to push this over the finish line?

**Comment by rhlsthrm** [comment]
https://paper.dropbox.com/doc/Dai-Card-UI-notes--Ao4evPh1Drp~hn4bee9jCyaNAg-zL59U1tYyoVVgNqaTEzD5

@hthillman started taking notes here also.

**Comment by ArjunBhuptani** [comment]
Stale, moving this here until we reprioritize it: https://github.com/ConnextProject/indra/issues/620
