### ISSUE TITLE
Upgrade CI

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#569]
2 things stand out as slowing down the CI process:

#### Soljs

We compile solidity from 4 modules (`contracts`, 'cf-apps', and funding + adjudicator contracts) using soljs which is way slower than solc compiled from c. We upgrade builder to include a solc binary & configure our solidity modules waffle.json files to use that instead of soljs.

#### We `make prod` too much

We `make prod` before each of our 4 set of tests and then again before `make push` in staging/prod CI. The full build before each set of tests isn't actually a huge deal bc those can run in parallel but that still clogs up our CI. Then we serially `make prod` again before pushing though, that's no bueno. Find a better way to `make prod` once and then not again during same CI run.

Saving testing data like docker images & build artifacts between jobs is complicated & vendor-specific in CircleCI. That kind of cross-job data storage might be inherently vendor-specific though. If we gotta do something vendor-specific, might as well use GitHub's CI since that'll keep everything in one place.

**Comment by LayneHaber** [comment]
So were switching off circle and to github? Nice!

Are there any other changes we'd need to make to allow this to happen or is what we have fairly portable?

**Comment by rhlsthrm** [comment]
Just need to translate the YML file and move the env vars.
