### ISSUE TITLE
Swapping between ETH and tokens in the deposit card doesn't show the proper values 

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#57]
## Steps to Reproduce (for bugs)
1. Type a number in the ETH section
2. Switch to tokens and change the already incorrect value
3. Switch back to ETH

**Comment by hthillman** [comment]
Whoops yeah. Missed a line in the value entry handler. Fixing now

**Comment by hthillman** [comment]
https://github.com/ConnextProject/indra/commit/c3feee3815d7c611caf5760d563d654e0e51395c
