### ISSUE TITLE
Build out dashboard

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/indra#572]
Right now, dashboard lets you look up channels by xPub and prints a nicely formatted JSON w/ human-readable numbers.

Additionally, we want to:
- [x] Look up channel by multisig address~
- [x]  Tag app instance ID (address) with associated monotonic app nonce so we can know which app instance is running
- [ ] See stats:
    - [x]  hub balances (ETH & SAI/DAI)
    - [x]  total value locked
    - [x]  tx count
    - [x]  average tx size 
    - [ ]  tx volume by time period
    - [x]  TVL
        - [x] sum free balances for user
        - [x] sum free balance for node
        - [x] sum app balances for user 
        - [x] sum app balances for node 
    - [x]  TVL: Payment volume ratio
    - [ ]  Gas paid by hub, by time period
    - [x]  channel count
    - [x]  Collateral ratio

To do this, we need:
- [x] new endpoints
    - [x] get channel state by multisig
    - [x] get all channel xpubs
    - [x] get all transfers
- [x] grab data from etherscan
     - [x] balances
     - [ ] gas prices

**Comment by rhlsthrm** [comment]
- Get Channel Free Balance (will require calling Node)

**Comment by LayneHaber** [comment]
> easily view Hub xpub state

what exactly does this mean? because there's not really any shared state between hub and client, we can basically *only* see the hub's channel state by querying the DB.

Or are you talking about balance of the address for collateral/gas purposes? (Which we would also want to be accessible)

**Comment by ArjunBhuptani** [comment]
^yeah this is what that means.

Going to make this time sensitive because we need these metrics once even a single wallet goes live

**Comment by hthillman** [comment]
Yeah, that's what I meant. will update to clarify

**Comment by hthillman** [comment]
closing. will open new issue w/ next todos
