### ISSUE TITLE
Polish cf-core types

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#574]
Various cleanup chores surrounding types. If any of these are big tasks on their own then they should be broken out into a separate issue but for now we'll group them all here.

 - [x] The StateChannelJSON type should live in a types module (types or cf-types) and be imported by cf-core instead of exported by it.
 - [ ] Above but for all those message types eg `WithdrawFailedMessage`.
 - [ ] making all of the enums consts so we can easily extend events a la #525
 - [ ] renaming from to initiator in the event emitted msgs
 - [ ] creating *Data types (e.g. DepositStartedMessageData type) so consumers of the package can use those easily
 - [ ] symmetric event data emission
 - [ ] verify `result` returned from the rpc methods 

See comments on PR #573 for more info

**Comment by LayneHaber** [comment]
We should probably break these out into separate issues, but keep this one as a reference check list

**Comment by LayneHaber** [comment]
Fixed event enums in #613 PR, still need to fix other miscellaneous enums

**Comment by LayneHaber** [comment]
Closing, broke this out into different issues:

- #623 making all of the `enum`s `const`s
- #624 event messages in types modules
- #625 rename `from` to `initiator`
- #626 creating `*Data` types
- #627 symmetric event emissions
- #628 rpc result assertion
