### ISSUE TITLE
Don't send failed transactions multiple times by default

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#575]
My daicard broke (proxy bytecode issues strike again!) And while trying to withdraw, the node sent the exact same tx 3 times:
1. https://etherscan.io/tx/0x1598a132703273c586d44d2d0de772ade0bcf0950747497c0ae8a71c544fb217
2. https://etherscan.io/tx/0xeb4b215312ebd608cd3d0c6fe5c9f6e049ec1cbd13748f25cfad4b7693336245
3. https://etherscan.io/tx/0x6ea3748d757ac33bdb3600f651119f4a8bbf5f6de04ad64431bb13a4308764f8

And, unsurprisingly, they all failed in the exact same way (technically, out of gas) meaning we burnt the full gas limit 2x times more than necessary.

Is retrying proxy deployment more than once ever useful? If so, we should detect these situations & only retry if there's a non-zero chance that retrying will succeed. But in general, this is an expensive default.

**Comment by LayneHaber** [comment]
In the CF code it by default retries transactions (for both withdraw/deposit iirc) 3 times. I doubt there are many cases where we would want to retry this multiple times in a naive manner. Wonder if there are major transferrable insights @rhlsthrm has from the v1 onchain transaction services?

**Comment by rhlsthrm** [comment]
The v1 onchain transaction service is slightly less naive in the sense that it parses error messages and decides to retry based on the actual failure.

**Comment by LayneHaber** [comment]
That's something we could pretty easily implement into the cf core stuff, would be a good addition imo

**Comment by ArjunBhuptani** [comment]
Fixed (with followup work happening in #599). Closing
