### ISSUE TITLE
Double sends to offline recipient sometimes

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#576]
**Describe the bug**
Sometimes I see that the client sends multiple times to the node. The recipient only receives one of the transfers though, which is very bad.

**To Reproduce**
1. Send to offline recipient

**Expected behavior**
Only send once.

**Comment by rhlsthrm** [comment]
This only happens sometimes, trying to figure out if it's related to double sending of propose messages.

**Comment by LayneHaber** [comment]
Could it be because the events for propose and install are the same and it's being handled twice on the client side/ believe this was fixed at the cf level in #577 and at the client level in #559

**Comment by rhlsthrm** [comment]
OK, will wait for the fixes on the other branches.

**Comment by ArjunBhuptani** [comment]
@rhlsthrm have you been able to repro this again now that fixes are merged? If not, we should close this

**Comment by ArjunBhuptani** [comment]
Closing for now since no one can reproduce this, we can reopen this if needed.
