### ISSUE TITLE
[cf] PR to counterfactual to make their master our working code

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#581]
Suggestion from Liam:

Create PRs for Counterfactual monorepo to get their master to mirror our working code. This way we can absorb changes from them.

**Comment by ArjunBhuptani** [comment]
We should definitely get into the habit of doing this for all changes asap. It would be really dumb to miss out on critical fixes from upstream because we diverged without realizing.

**Comment by rhlsthrm** [comment]
Yep, this is difficult right now since we've diverged quite a bit already, but we need to make a proper diff and make the PR work. I'll work with @bohendo on the best way to move on this.

**Comment by bohendo** [comment]
Not a high priority, especially given future research work is moving to a new repo: statechannels/monorepo
