### ISSUE TITLE
[Client] Implement client in sample react native repo and add docs

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#585]
As a followup to https://github.com/ConnextProject/indra/issues/474, implement the client in a sample react-native repo with documentation.

**Comment by LayneHaber** [comment]
see repo [here](https://github.com/ConnextProject/ConnextReactNative) and updated docs [here](http://docs.connext.network/en/latest/userDocumentation/quickStart.html#react-native)
