### ISSUE TITLE
[client] Store has two prefixes

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#586]
**Describe the bug**
Store entries in the client are using two prefixes:

```"INDRA_CLIENT_CF_CORE:INDRA_CLIENT_CF_CORE/xpub6DXwZMmWUq4bRZ3LtaBYwu47XV4Td19pnngok2Y7DnRzcCJSKCmD1AcLJDbZZf5dzZpvHqYzmRaKf7Gd2MV9qDvWwwN7VpBPNXQCZCbfyoK/channel/0xFd7AaC36F74c6Fb4791191bE8c152d2A68a3163c"```

Doesn't seem to be breaking anything, but definitely not stored as intended. Changing this should be tested against clients that were using stores with the double prefix.

**Comment by rhlsthrm** [comment]
This actually is the case in the hub and breaks channels in the hub. We need to fix this ASAP.

**Comment by rhlsthrm** [comment]
Update: ran the following queries on staging to fix the node DB:

```sql
# find how many channels are messed up
select count(path) from node_records where path like 'ConnextHub%';

# actual transaction
begin;
# update values before paths
update node_records set value = replace(value::text, 'ConnextHub', 'INDRA_NODE_CF_CORE')::json where path like 'ConnextHub%';
# update paths
update node_records set path = replace(path,'ConnextHub','INDRA_NODE_CF_CORE');
commit;
```

**Comment by LayneHaber** [comment]
wait, this was all talking about client side stuff.

this is an issue with the store implementation, specifically [here](https://github.com/ConnextProject/indra/blob/393fa248201fc6ccfc78b2408d65d63a3df79d91/modules/daicard/src/utils/store.js#L76) and [here](https://github.com/ConnextProject/indra/blob/393fa248201fc6ccfc78b2408d65d63a3df79d91/modules/daicard/src/utils/store.js#L41) since in cf-core the prefix is also being added [here](https://github.com/ConnextProject/indra/blob/393fa248201fc6ccfc78b2408d65d63a3df79d91/modules/cf-core/src/store.ts#L143)

again, not sure if it's a *huge* issue since its not breaking anything, but it isn't cute

**Comment by rhlsthrm** [comment]
Yeah, wait that set method is not right at all: https://github.com/ConnextProject/indra/blob/393fa248201fc6ccfc78b2408d65d63a3df79d91/modules/daicard/src/utils/store.js#L41...

We should definitely fix this.
