### ISSUE TITLE
[cf, node, client] Relay events with better subjects

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#589]
Since we are using NATS, we should make use of the subjects better. I'd propose using the multisig address in the subjects, such as:

`indra.client.${xpub}.createChannel.${multisigAddress}`

This will allow us to subscribe and unsubscribe more granularly without having to bind listeners and stuff.

**Comment by ArjunBhuptani** [comment]
This will break backwards compatibility right?

**Comment by LayneHaber** [comment]
These NATS messages are only being used internally, don't think it would break anything.

This could clean up the code a fair amount *but* it should also be solved by the symmetric event emission in cf-core (at which point these publishings should be deleted anyway imo). See #574

**Comment by rhlsthrm** [comment]
> This could clean up the code a fair amount but it should also be solved by the symmetric event emission in cf-core (at which point these publishings should be deleted anyway imo). 

This might be solved by event emission, but maybe not. The case I'm trying to solve is:

When the client installs an app, they want to listen for the install event to make sure it got installed. Instead of binding the callback and listening for all events, we could listen for only the specific app instance install event because the message subject would be deterministically sent as `indra.client.${multisig}.install.${appInstanceId}`. Having this granular messaging will be really helpful for a pubsub based, distributed, event driven system.

I think it would be easy to implement. On the client and hub listeners we can just do things like:

```ts
cfCore.on(INSTALL_EVENT, data => {
  messaging.publish(`indra.client.${this.multisig}.install.${data.appInstanceId}`, data);
});
```

**Comment by ArjunBhuptani** [comment]
Include `chainId`

**Comment by ArjunBhuptani** [comment]
We should have a larger discussion about nats message subjects and backwards compatibility

**Comment by ArjunBhuptani** [comment]
Opening tracking issue here: https://github.com/ConnextProject/indra/issues/712

**Comment by ArjunBhuptani** [comment]
Closing this because stale
