### ISSUE TITLE
Trying to deploy on fisco-bcos, any suggestion?

### ISSUE THREAD

**Issue by walter211** [ConnextProject/indra#595]
**Is your feature request related to a problem? Please describe.**
We are wokring on a supply chain financial project senerio, there are some light transaction need to be supported.

**Describe the solution you'd like**
Fisco-Bcos is a consortium blockchain like HyperLedger Fabric, but its contract vm is evm-like.

**Describe alternatives you've considered**
I am trying to make a product of concept app, cause of i am newbie for this, any suggestion will be appreciated!

**Additional context**
Main problem now is we need to make a adaptive layer for the connection of access mechanism on fisco-bcos.

**Comment by rhlsthrm** [comment]
Can you deploy the contracts? We have scripts for all the deployment and setup that you can try to modify.

**Comment by walter211** [comment]
Actually, I do not worried about the contract deployment, fisco-bcos support erc20 token. The problem which I really wonder to know is the adaptation cost for the node connection

**Comment by ArjunBhuptani** [comment]
@walter211 let us know how this goes, we're interested in supporting more EVM chains

**Comment by LayneHaber** [comment]
> Actually, I do not worried about the contract deployment, fisco-bcos support erc20 token. The problem which I really wonder to know is the adaptation cost for the node connection

are you asking what specifically you would need to change about the node software to work with your chain? would help if you described your use-case in a bit more detail. im guessing there would be some ops stuff to change with deploying the node for dev, etc (cc @bohendo).

also, we tend to be more high touch on our [discord](https://discord.gg/xWf8hs) so don't hesitate to reach out there!

**Comment by ArjunBhuptani** [comment]
Stale, closing
