### ISSUE TITLE
[cf-core, node] Deposit retry logic

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#599]
Deposits are only tried once, would be good to have them retried based on common error messages.

Should also make sure we're adding any hub deposits and create channel txs into the `onchain_transactions` table in the hub DB

**Comment by bohendo** [comment]
I'm tentatively downgrading this to priority lvl 3 bc it's not clear to me which situations would be useful to retry on, eg which "common error messages"?

The "and also" bit might be worth breaking out into a separate issue though but that also seems like it could be a p3 issue.

**Comment by ArjunBhuptani** [comment]
Looks like the "and also" piece made it into this issue: https://github.com/ConnextProject/indra/issues/792

**Comment by LayneHaber** [comment]
Implemented in the node deposit service, closing
