### ISSUE TITLE
[Bug] why .env is not loaded 

### ISSUE THREAD

**Issue by walter211** [ConnextProject/indra#604]
**Describe the bug**
launching this with vscode, error shows "[Nest] 13194   - 12/06/2019, 5:57 PM   [ExceptionHandler] Invalid Messaging Url: [""]"

just following this :
https://github.com/ConnextProject/indra/blob/staging/modules/node/README.md
I dig into this found that because .env file was not loading.

**Comment by rhlsthrm** [comment]
I'd highly recommend to follow the full repo root instructions for quickstarting. It looks like we stopped reading the .env file, so these instructions are outdated. Sorry about that. I'll file a bug report to fix this. We inject the env vars through the ops scripts in the root.

**Comment by walter211** [comment]
> I'd highly recommend to follow the full repo root instructions for quickstarting. It looks like we stopped reading the .env file, so these instructions are outdated. Sorry about that. We will get this fixed, but in the meantime can you use the main repo instructions? We inject the env vars through the ops scripts in the root.

thx! I will try.

**Comment by walter211** [comment]
emmm……I want to deploy node independently, may I get a way to do that?

https://github.com/ConnextProject/indra/issues/595

Here is what i am tring to do

**Comment by rhlsthrm** [comment]
Until we fix the .env issue, you'll have to manually set the env vars with `export`.

**Comment by walter211** [comment]
> Until we fix the .env issue, you'll have to manually set the env vars with `export`.

roger that, thx!

**Comment by ArjunBhuptani** [comment]
@walter211 let us know how this goes! We're interested in supporting this if we can

**Comment by ArjunBhuptani** [comment]
For now, we're just updating docs to reflect manually setting env vars with export
