### ISSUE TITLE
[node] Broken mainnet channels after proxy factory address additions

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#610]
After adding proxyFactoryAddress to Node store, we see 5 channels on mainnet that could not calculate the multisig address. This means they will not be able to withdraw and any deposited funds will not be recoverable.

Affected multisig addresses:
```
0x1508eCF431F5DeF63d708fa657a9c8dB5d153a78
0xf6393A66a5A667D729b2b287117055466EDdDfBb
0x99A4c63cFf0Dcd50eeCF7B867C8a7aC89696A997
0xB559B1cad8eE3ea676fFC2eBA0a115D3BACD2b67
0x60EBf23291F0a0Ad51b01f997E37441217D24d7D
```

**Comment by rhlsthrm** [comment]
Probably low priority until one of these owners complains.

**Comment by LayneHaber** [comment]
personally id rather just do it while its top of mind

**Comment by rhlsthrm** [comment]
Well the thing is we can't do anything about it unless we find the proxyFactoryAddress that generated the bytecode that calculates the multisig address.

**Comment by ArjunBhuptani** [comment]
Closing for now, we can reopen if someone complains about this issue, but there's a good chance these were channels we used internally for testing so :man_shrugging:

**Comment by bohendo** [comment]
No I did a deep investigation into `0x1508eCF431F5DeF63d708fa657a9c8dB5d153a78` and have confirmed that these finds have been burned (prob true for the others as well). Even if an owner complains, there's nothing we can do other than offer a refund
