### ISSUE TITLE
Get bot farm tests into CI 

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#621]
Run on releases but not on hotfixes

**Comment by ArjunBhuptani** [comment]
+ refactor bot js file to use test suites (and asserts) and wire that into the bot farm bash script so that failures get caught more strictly

**Comment by bohendo** [comment]
Here's my vision for the future of bot tests:
 - We don't have separate bot & bot-farm tests, just one big tests suite and a chunk of those tests cover concurrency
 - Bot tests move out of bash & into mocha or a similar JS framework (I'm not a huge fan of jest tbh..). Bash worked well for hacking together a quick & dirty set of tests but if we want to flesh these out & start hitting edge cases w stricter focus, we should probably get our tests into JS.
