### ISSUE TITLE
[cf-core, client, node] Ensure Promises *always* resolve

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#641]
We've run into at least two cases so far where unresolved promises have blocked execution and caused bugs that are hard to track down.

We should do a global search of the codebase and ensure that promises (even in edge cases where inputs fail validation unexpectedly) *always* resolve or reject in some way. This will also help with tracing errors through the stack.

**Comment by LayneHaber** [comment]
I know @rhlsthrm has done this a few times throughout the CF side from that weird store issue from a while back. 

I think the higher priority thing would be sorting out the queue issues when the client goes offline unexpectedly)

**Comment by rhlsthrm** [comment]
Let's make sure on our end we use this pattern:

```ts
await Promise.race([
  <Resolving promise>,
  delayAndThrow(30_000), // util function that returns Promise that throws after a certain amount of time
]);
```

I've seen instances in the codebase where we do the old way of setTimeout, this way is much cleaner and simpler.
