### ISSUE TITLE
[ops] Remove CircleCI build check

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#643]
It v annoying 

![Screenshot from 2019-12-13 15-28-31](https://user-images.githubusercontent.com/22877754/70838466-3006d500-1dbd-11ea-9288-16743897f0a3.png)

**Comment by bohendo** [comment]
I think it's still hanging around old PRs but I see it's gone in some of the newer ones. Closing this now but we should reopen if I keeps annoying us 

![image](https://user-images.githubusercontent.com/8527067/70972428-61d3b080-20c9-11ea-8ddf-103a27becd09.png)
