### ISSUE TITLE
Merge cf-types into types

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#649]
**Is your feature request related to a problem? Please describe.**

cf-types is almost never changing these days and it adds an extra, unnecessary step to `npm-publish` that could potentially fail (especially given a spotty internet connection).

We have no reason to keep a chunk of our types separate.

**Describe the solution you'd like**

All our types and interface definitions should be in one place. This will make for easier interface management & make it easier to find the types you're looking for. We will have fewer dependencies that might get out of date and gives a better devex.

**Comment by LayneHaber** [comment]
Actually a huge pain when I'm trying to debug things, so I would even upgrade this to a `p2`
