### ISSUE TITLE
Consolidate Contracts

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#676]
**Is your feature request related to a problem? Please describe.**

There's a bit of overlap between our "contracts" module and the "cf-apps" one eg there are identical SimpleTransferApp and SimpleTwoPartySwapApp contracts in each of these.

Anyone have any strong feelings regarding the long-term layout of our contracts?
Any reason we shouldn't consolidate our OG contracts w the cf-apps modules?
For that matter, is there any reason we shouldn't consolidate *all* our contracts? 

**Describe the solution you'd like**

Put all our contracts (+ contract tests) into one module. This would make it simple to add contract tests to CD as well which is IMO mission-critical before we start digging into the audit issues.

**Comment by ArjunBhuptani** [comment]
No strong feelings but let's do this after finishing writing tests?

**Comment by LayneHaber** [comment]
done, closing
