### ISSUE TITLE
Metamask Demo Deposit Borked

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#68]
## Expected Behavior
Depositing into channel from metamask using the deposit button is broken.

## Current Behavior
Does not allow for ETH deposits, or token deposits to channel from metamask. Currently, metamask will say the transaction failed, while there is no indication of that in the application.

**Comment by ArjunBhuptani** [comment]
Commented on PR: it fixes metamask deposit but autosigner deposit now seems to be broken. Was it tested with both?
