### ISSUE TITLE
[cf-core] Withdrawal Commitment Events

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#698]
**Describe the bug**
No events are thrown when the withdrawal commitment is created. This is anti-pattern for the rest of the code base. That being said, I also don't think its appropriate to use `WITHDRAWAL_CONFIRMED`, or `WITHDRAWAL_STARTED` if it isn't being submitted to chain. (Though there could be an event when the node does that for the user.)

Thinking we'll need a new `WITHDRAWAL_COMMITTED` event, but open to discussion.

**Comment by ArjunBhuptani** [comment]
Is this still relevant?

**Comment by LayneHaber** [comment]
no need for event/fixed, closing
