### ISSUE TITLE
[Client] Async callback for Swap never invoked when node rejects install

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#700]
To reproduce, call swap with an incorrect swap rate so that node rejects the install (or any other mechanism to get node to reject).

A failing test for this already exists in swap itests.

**Comment by LayneHaber** [comment]
What exactly is expected behavior, that a `REJECT_INSTALL` is fired? And I'm assuming it's [this](https://github.com/ConnextProject/indra/blob/4a762d5e1734d76f8e3c78e7fe3bdbc2eab8051d/modules/test-runner/src/swap/swap.test.ts#L236) test?

**Comment by ArjunBhuptani** [comment]
Yes it's that test. Expected behavior is that client rejects promise when `REJECT_INSTALL` is fired. 

It's the same as this issue that was just opened: https://github.com/ConnextProject/indra/issues/700

**Comment by ArjunBhuptani** [comment]
Closing because we have the other one
