### ISSUE TITLE
[test-runner] ChannelProvider tests

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#703]
- [x] Happy case: Bot A1 can be instantiated with a channelProvider generated from Bot A
- [x] Happy case: Bot A1 can call the full deposit → swap → transfer → withdraw flow on Bot A
- [x] Bot A1 tries to call a function when Bot A is offline
- [ ] Bot A1 tries to reject installing a proposed app that bot A has already installed?

**Comment by LayneHaber** [comment]
Skipping this test for now and closing issue

``` Bot A1 tries to reject installing a proposed app that bot A has already installed```
