### ISSUE TITLE
[messaging, client, cf-core] Tracker: Simplify/standardize messaging

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#712]
Tracker issue to refactor messaging to be more robust. High priority because this will be a major breaking change.

Includes tasks such as:
- Improve/standardize message subjects and move those definitions into types (formerly: https://github.com/ConnextProject/indra/issues/589)
- Complete NATS authentication tasks (e.g. https://github.com/ConnextProject/indra/issues/325)
- Find ways to future-proof messaging

**Comment by ArjunBhuptani** [comment]
Includes https://github.com/ConnextProject/indra/issues/325 and possibly https://github.com/ConnextProject/indra/issues/397?

**Comment by ArjunBhuptani** [comment]
Does this include #397?

**Comment by kthomas** [comment]
> Does this include #397?

Yes.

**Comment by LayneHaber** [comment]
Other messaging related issues:
- #626 
- #625 
- #589 
- #325

**Comment by ArjunBhuptani** [comment]
Closing this because we've done all of these tasks - hooray!
