### ISSUE TITLE
[client, node] Move payment profile creation to node and management to external service

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#720]
Needed for Graph integration (and all other paid users).

Will warrant a speccing/brainstorming call to think through what data we need to push through the API and what the interface should look like.

**Comment by LayneHaber** [comment]
Let's say Tuesday morning after the kt call? @ArjunBhuptani @hthillman

**Comment by ArjunBhuptani** [comment]
I have another call scheduled - could we do 1 hour later? (9am PT)

**Comment by LayneHaber** [comment]
Updated to tracker, other related issues:
- #599 

### Service consumption

Needs data from:
- `onchain_transactions` table
    - make sure `collateral`, `withdraw`, `deposit` is flagged
    - make sure transactions properly added in the code base
- `transaction` view
- SOLUTION: Put it all into a separate view w/read access
    - hash recipient xpub
    - Service only gets access to this view
    - Should include:
        - onchain transactions for channel w/reason flags
        - transaction view data for user
        - Current user free balance at time of transaction? (best way to put channels into over-/under-collateralized categories tbd)

**Comment by ArjunBhuptani** [comment]
Duplicate of: https://github.com/ConnextProject/indra/issues/802
