### ISSUE TITLE
Remove hard-coded list of supported networks

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#735]
First attempt at deploying an indra node to ETC's kotti testnet made good progress.. but failed because we have a hardcoded list of supported networks in `modules/types/src/app` and kotti isn't on it.
```
export const SupportedNetworks = {
  ganache: "ganache",
  goerli: "goerli",
  homestead: "homestead",
  kovan: "kovan",
  rinkeby: "rinkeby",
  ropsten: "ropsten",
};
```
Ironically, the fact that it's not on this list of supported networks might be the *only* reason it's not supported.. If we didn't hardcode this list in the first place then we might be able to support all networks by default

**Comment by ArjunBhuptani** [comment]
So it makes sense to have a supported networks check in the node - we don't want people trying to open channels on unsupported networks and not knowing what's going on. That being said, this should be something that's configurable on node deploy.

Any good ideas on how to do that?

**Comment by bohendo** [comment]
I think supported networks should be enforced by the address book. As long as contracts are deployed to some given network, then that network is technically supported. Nobody's going to "accidentally" deploy contracts to kotti then configure the node to use the kotti entry of the address-book w a kotti ethprovider, that's too much work. And once a node's set-up to run on some network, user's can't accidentally use it on a different one.

**Comment by bohendo** [comment]
PS part of removing the list of supported networks should be replacing any reference to network names with chain ids or similar
