### ISSUE TITLE
[client, test-runner] Promises not properly rejecting

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#741]
**Describe the bug**
Client isn't properly rejecting promises when the `REJECT_INSTALL_EVENT` is caught.

Seems likely that the event is thrown before the promise is created.

**To Reproduce**
Run [this](https://github.com/ConnextProject/indra/blob/140a4336ff8ac738492fe28889608fbe10ffd16b/modules/test-runner/src/transfer/asyncTransfer.test.ts#L81) test

**Comment by ArjunBhuptani** [comment]
Duplicate of #700. Closing the older issue

**Comment by LayneHaber** [comment]
Should be closed with #736
