### ISSUE TITLE
"Channel Information:" box doesn't refresh

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#75]
## Expected Behavior

I, the user, am a control freak and I want to know that the Channel Information box knows that I want it to refresh.

## Current Behavior

No refresh button

## Possible Solution

Preferably, wire up a refresh button to the channel balance poller. Or at least give me an [idiot button](https://usabilla.com/blog/faking-interaction-placebo-ux-design/).

## Context

I'm trying to debug channel information that's not updating consistently after a deposit. I'd feel better if I had a button to click that made me feel more confident that this channel information is up to date. Hard to know where the problem lies when I can't tell if the info presented to me is up to date.

## Your Environment

* Version used: Commit ec80f89
* Browser Name and version: Firefox version 66.0b1
* Operating System and version (desktop or mobile): MacOS desktop version 10.14.2 (18C54)
* Link to your project: this is it

**Comment by LayneHaber** [comment]
Are we still maintaining the wallet UI @ArjunBhuptani ? otherwise ill close this

**Comment by bohendo** [comment]
Let's focus on the dashboard in Indra and the card for the end-user interface. We'll reopen a similar issue later if we want to polish the wallet.
