### ISSUE TITLE
[store] Add store module happy case tests

### ISSUE THREAD

**Issue by pedrouid** [ConnextProject/indra#753]
Storage tests:
- [x] happy case: instantiate with window.localStorage
- [x] happy case: instantiate with AsyncStorage
- [x] happy case: instantiate with MemoryStorage
- [x] happy case: instantiate with FileStorage
- [x] happy case: localStorage should include multiple keys
- [x] happy case: AsyncStorage should include a single key
- [x] happy case: MemoryStorage should include a single key
- [x] happy case: FileStorage should include a single key
- [x] happy case: FileStorage should create a store directory
- [x] happy case: FileStorage should create a file per key inside directory
- [x] happy case: FileStorage should create a files with unique name

Store tests:
- [x] happy case: set & get the same path consecutively
- [x] happy case: get partial matches when available
- [x] happy case: reset the whole store state 
- [x] happy case: backup state when provided a backupService
- [x] happy case: restore empty state without backupService

**Comment by LayneHaber** [comment]
@pedrouid can you review pr #754

**Comment by LayneHaber** [comment]
Fixed by #754
