### ISSUE TITLE
@connext/client missing dependency via TS Webpack

### ISSUE THREAD

**Issue by RyRy79261** [ConnextProject/indra#774]
**Describe the bug**
When attempting to use the client package in a React + TS + Webpack project, an error is thrown in the client `utils.js` file stating `@connext/contracts` is required but missing

**Screenshots**
![image](https://user-images.githubusercontent.com/10461622/72964706-442df100-3dc3-11ea-8fab-520f6833840e.png)

**Your Environment**
* Client version used: 4.0.1
* Node version used: 13.6.0
* Chain used: NA
* Browser Name and version: NA
* Operating System and version (desktop or mobile): Manjaro KDE
* Link to your project: Private

**Comment by bohendo** [comment]
New export was missing from `@connext/contracts`, publishing new release of this package fixed the problem
