### ISSUE TITLE
[cf-core] TypeError: Cannot read property 'abi' of undefined

### ISSUE THREAD

**Issue by pedrouid** [ConnextProject/indra#777]
**Describe the bug**
Updating the client from 3.0.1 to 4.0.4 triggered this issue on WalletConnect test-wallet using react dev build.

**To Reproduce**
1. Clone [walletconnect-test-wallet](https://github.com/WalletConnect/walletconnect-test-wallet)
2. Update connext dependencies from 3.0.1 to 4.0.4
3. Install dependencies using `npm install`
4. Run app in dev environment using `npm run start`

**Expected behavior**
App should load with any errors

**Screenshots**
<img width="958" alt="Screenshot 2020-01-23 12 37 33" src="https://user-images.githubusercontent.com/10136079/72981900-2326c980-3dde-11ea-9bb7-1bd7191bd3a9.png">

**Your Environment**

* Client version used: 4.0.4
* Node version used: 4.0.4
* Chain used: rinkeby
* Browser Name and version: Brave 1.2.43
* Operating System and version (desktop or mobile): macOS Catalina 10.15.2
* Link to your project: https://github.com/WalletConnect/walletconnect-test-wallet

**Additional context**
The same issue happens with production build using `npm run build`

**Comment by rhlsthrm** [comment]
Fixed in Client v4.0.5. I had to make this fix: https://github.com/ConnextProject/indra/commit/b9e801375c923e1eb7a89057ef442019806a0347#diff-51ad5589022cdf9283779ab57005ece4R6.

Unclear why it was like this and how it worked before, going to loop in @bohendo to see if he has more info.
