### ISSUE TITLE
TRANSFER_CONFIRMED_EVENT ?

### ISSUE THREAD

**Issue by balasan** [ConnextProject/indra#781]
**Is your feature request related to a problem? Please describe.**
Currently (as of client v 4.05) there is not a useful event being fired telling me that an incoming transfer has been successfully processed. I'm seeing the `UPDATE_STATE_EVENT` but it doesn't contain the `meta` field of the original transaction, so I have no way of attaching a handler to a specific transaction.  

**Describe the solution you'd like**
seems like there should be a TRANSFER_CONFIRMED_EVENT fired [here](https://github.com/ConnextProject/indra/blob/e12cf6f9b32ddae1c6f05977a5e0958df710945f/modules/client/src/listener.ts#L358): with original msg as the payload

**Describe alternatives you've considered**

**Additional context**
I saw a comment in another section of the codebase some TRANSFER event types being deprecated but not sure what's up with that.

**Comment by rhlsthrm** [comment]
Hey @balasan, thanks for the question! The event names are documented here: https://docs.connext.network/en/latest/userDocumentation/advanced.html#event-monitoring. We have an event emitted for `RECEIVE_TRANSFER_FINISHED` which is what you are looking for. It is in the code [here](https://github.com/ConnextProject/indra/blob/hotfix-for-daicard-to-nodejs/modules/client/src/controllers/ResolveConditionController.ts#L205) which is a couple of functions downstream from where you linked. The payload is a `paymentId` which you can use in the [`client.getLinkedTransfer`](https://github.com/ConnextProject/indra/blob/staging/modules/client/src/connext.ts#L252) method to retrieve all the details.

**Comment by rhlsthrm** [comment]
I'll close this for now but please let us know if you have more issues!
