### ISSUE TITLE
[contracts] Deploy new contracts

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#819]
Blocked by #601 

Need to deploy new contracts to rinkeby and mainnet, as well as publish a new `@connext/contracts` package

**Comment by LayneHaber** [comment]
Should also consider #775

**Comment by ArjunBhuptani** [comment]
Also potentially blocked by #821 and whatever comes out of our disputes discussions

**Comment by LayneHaber** [comment]
Done, closing
