### ISSUE TITLE
Cannot read property 'currentProvider' of undefined [Brave Browser]

### ISSUE THREAD

**Issue by bohendo** [ConnextProject/indra#82]
## Expected Behavior

Should detect an injected `window.web3` and, if it doesn't exist, handle that case better than by crashing.

## Current Behavior

Bug occurred on Brave Browser, maybe it's doing something unusual while injecting Metamask's web3?

## Possible Solution

1st step: reproduce on Brave browser

## Steps to Reproduce (for bugs)

1. Run `npm start`
2. Open app in Brave browser

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by ArjunBhuptani** [comment]
Was this ever fixed? @bohendo

**Comment by LayneHaber** [comment]
My guess is this was the cookie error we saw on prod? Closing until it pops up again.
