### ISSUE TITLE
[contracts] Restrict recipient of transfer apps

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#824]
Inside `SingleAssetTwoPartyCoinTransferInterpreter.sol`, add statement to:
```
require(outcome[0].to == HardcodedAddress); 
// make sure outcome address is correct, this is just an example
```

Where `HardcodedAddress` is the indexer address.

In the app itself, logic should be enforced so indexer is only allowed to claim payments and node is only allowed to make payments (i.e. make it unidirectional).

Require in offchain app installation that node address is sender and indexer is the recipient.

**Comment by ArjunBhuptani** [comment]
We can also enforce unidirectionality here.

Note that in this case, we're just writing this custom interpreter for Graph and then having them create and use a custom address-book.json rather than including it as a core part of the stack.

**Comment by ArjunBhuptani** [comment]
I'm going to close this issue for now because it wont be something that is generalizable to the rest of the stack (i.e. it's a Graph-specific need which we can implement for them separately).
