### ISSUE TITLE
Config sync from client/hub

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#85]
## Expected Behavior
Client should sync with the hub for addresses/rpc urls on different networks.

## Possible Solution
Should address this in the `getClient` function, and enforce it on `start` in the client.

Needs an endpoint for the hub (done)

**Comment by LayneHaber** [comment]
@rhlsthrm you merged @bohendo 's PR for this right?

**Comment by rhlsthrm** [comment]
Yes.
