### ISSUE TITLE
Make hub env-vars indra-specific

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#87]
If users have existing env variable that are called the same thing, hub-run scripts will fail.

We should add "indra-" before all indra-specific env variables to avoid collisions.

(This happened with Ujo and the DB-URL variable)

**Comment by bohendo** [comment]
Glad you noticed this, I can fix it today

**Comment by bohendo** [comment]
This has been fixed by Indra commit 59725dbd22ab138b42170c4fc89b9a42b599b8aa

**Comment by bohendo** [comment]
Well, it's definitely fixed when deploying locally using docker. If this problem is still present (eg while deploying locally) then we can reopen & address those issues too
