### ISSUE TITLE
[types] Types changes from interfaces review

### ISSUE THREAD

**Issue by rhlsthrm** [ConnextProject/indra#957]
- [x] Swap method should return a `SwapResponse`
- [x] Transfer method should not return `any`
- [x] CREATE_TRANSFER event name is inconsistent
- [x] Remove CfCoreController class in node
- [x] Remove signerAddress, consolidate on freeBalanceAddress
- [x] Remove getAppState
- [x] Rename getAppInstance to getAppInstanceDetails
- [x] Remove verifyAppSequenceNumber
- [x] Change all references to `appId`, `appInstanceId`, `appHash`, etc to `appIdentityHash`.

**Comment by bohendo** [comment]
Note re renaming `appId`: a few db tables include `appId` columns but these appear to be distinct from `appIdentityHash` as they point to the db primary index of a row in the apps table. So these should not be renamed & should be kept as-is.
