### ISSUE TITLE
Review deploy documentation

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#96]
The documentation should be so great even @LayneHaber can deploy it if needed with everyone gone ;)

This is done, and it is easy, but just making sure it's updated before we deploy. Mostly a checkmark here so it doesn't slip through the cracks.

Should also make sure there is a dropbox document stored in the release that outlines the security vulnerabilities/concerns around the infrastructure.

**Comment by bohendo** [comment]
The README was reviewed & updated in commit 15cd56a. If any steps aren't clear, let's open a separate issue for specific problems to be addressed.

Closing this now, security vulnerabilities/concerns will be addressed as part of the [mainnet checklist](https://github.com/ConnextProject/indra/issues/101)
