### ISSUE TITLE
Hot Wallet Autodeposit

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#97]
"A way for hub to autodeposit into the contract/hotwallet when/if funds run low. I'm a little hesitant on this one cause, if something goes horribly wrong, we can burn through a LOT of capital very quickly." -- @ArjunBhuptani 

We could rate limit the amount of times a wallet does this automatically without manual approval. Personally, I think this is something we can monitor from the dashboard for v1 and upload manually?

Biggest thing for that is making sure the multisig is set up so we don't have to wait for one person to be up before we can reload the hot wallet (assuming people dont want to or dont have substantial personal eth).

**Comment by bohendo** [comment]
The plan is to create a script to move funds from the hub's wallet (using the private key loaded into the hub's secret store) to the contract.

Seems to strike a good balance, simple enough that anyone w ssh keys can give the contract collateral w a single command, manual enough that if the contract is getting drained, etc then no funds will move automatically.

**Comment by bohendo** [comment]
I've created a script in commit a8aa8c8 to help easily move funds from the hub's wallet (using the private key loaded into the hub's secret store) to the contract.

Seems to strike a good balance, simple enough that anyone w ssh keys can give the contract collateral w a single command, manual enough that if the contract is getting drained, etc then no funds will move automatically.
