### ISSUE TITLE
[daicard] Use legacy daicard address when attempting to migrate

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#978]
v2 daicard uses the CF derivation path when creating your in-browser address.

This is ok, but we need to still suport the Ethereum derivation path in the case where the user needs to migrate funds from a v1 DaiCard. (we can always withdraw from v1 dai card at ethereum path and send to v2 dai card at CF path)

**Comment by LayneHaber** [comment]
closing, stale
