### ISSUE TITLE
Hot Wallet Robustness

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#99]
Hot wallet may also not be the best way to store funds for the hub, we'll need a more robust way to store funds for the hub. You can be sure that whatever wallet/multisig is being used will be probed a lot by potential attackers. Ideally, this should be a clean wallet/address/multisig with no tx history and only the amount of funds we need

We also need multisig so everyone can transfer dai/eth to the hub wallet

**Comment by ArjunBhuptani** [comment]
A hot wallet is fine. I just want to make sure we aren't using the main Connext account for this lol

**Comment by LayneHaber** [comment]
Suggestion that came up: look into AWS Secret Management for securely rotating hot wallet keys, managing permissions, etc.

**Comment by LayneHaber** [comment]
Need to be moved over to appropriate AWS ownership, @rhlsthrm think you're the only one who can get that done

**Comment by LayneHaber** [comment]
Above is an optimization, can close, and note to improve in ice box
